AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  boatregisterapi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: An AWS lambda function that sits behind an api gateway.
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: MAIL_*
        - SNSPublishMessagePolicy:
            TopicName: boatenquiry
        - DynamoDBCrudPolicy:
            TableName: *
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:ListTables
              Resource: '*'
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /boatregister-api
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /public/{proxy+}
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /{scope}/{table+}
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api5:
          Type: Api
          Properties:
            Path: /public/{table+}
            Method: ANY
      RuntimeManagementConfig: {}
